### ISSUE TITLE
The OPDS feed does not work with certain readers on Android devices.

### ISSUE THREAD

**Issue by Nosirus** [mcpierce/comixed#440] opened 2019-04-15 16:13 UTC
Hello and thank you for ComiXed is exactly what I have searched for a long time

But nothing to do, with lots of android application and ipad (except chunky I wanted to try before taking the pro version) and full combination of url, I can not access it with OPDS

**Comment by mcpierce** [comment] 2019-04-15 16:45
You're welcome! I'm hoping the app becomes something a lot of people will find useful.

The OPDS support isn't in a released version yet (latest is 0.2.0): it's only in the current development releases (anything marked as 0.3.9-SNAPSHOT).

Can you give me some more details?
 * Which ComiXed JAR file did you try to use?
 * What URL did you use in the reader?
 * Are you able to go that same URL from a browser?

**Comment by Nosirus** [comment] 2019-04-15 18:59
I tried the last three releases, the last : comixed-app-0.3.9-SNAPSHOT-20190415002550

For the url i try : ip:7171, ip:7171/opds, ip/opds:7171, with or without http:// and /opds

I can access on the network, on the management page and view my comics, but when I try ip:7171/opds in my navogator i get this [Link](https://imgur.com/yudZGqB)

I think he is well on his way to being the worthy successor of ComicRack! that in addition I start to have trouble using since I leave all softly windows
(sorry for my english level...xD )

**Comment by mcpierce** [comment] 2019-04-15 19:05
@Nosirus So the output in the image you showed looks about right. Try changing it to:

    http://IP:7171/opds/all

and see if you can see the comics.

**Comment by Nosirus** [comment] 2019-04-16 12:57
with Marvin 3 ipad app and under linux I can see them by adding /all but I have 5000+ comics so complicated to navigate and he downloads only

with android apps it does not work and i often get in the terminal
`2019-04-16 14:31:00.787  WARN 1638 --- [nio-7171-exec-5] .w.s.m.s.DefaultHandlerExceptio
nResolver : Resolved [org.springframework.web.HttpMediaTypeNotAcceptableException: Could
not find acceptable representation]`

if I run comixed under windows (with 2 different computers) nothing to do, I do not know if it comes from windows

**Comment by mcpierce** [comment] 2019-04-16 13:05
I'm not sure what "it" refers to in that last sentence. The JAR file runs on all platforms, no features are disabled on any.

The exception you're seeing in the terminal seems to be a local exception, is that correct? If so, than that means that the app you're using doesn't know how to open a file with a MIME type of "application/x-cbr". What app are you using on Android and does that app support CBR/CBZ files?

Please bear in mind that the OPDS support is new, and not completed at this time. Right now it only supports letting the client download the full library. There are features to be completed still, including authentication, navigating reading lists, retrieving unread-only comics, etc. But they're not done at this time.

**Comment by Nosirus** [comment] 2019-04-17 02:03
I tried on android : challenger viewer, fbreader, librera reader, perfect viewer, moon+, astonishing comic reader (yes I'm trying a lot ...)
I will wait for the full support of opds
For chunky, the support of comics read and retrieving unread comics is already integrated?

**Comment by mcpierce** [comment] 2019-04-17 12:22
No, the only portion of OPDS that is completed as of today is the ability for any reader (not just Chunky) to access the **/all** feed, get the list of comics, and pull down individual comics. I'm not sure what's going on with the Android readers you're testing: all of the ones I've used (Chunky, KyBook 3, PocketBook) all read the OPDS feed and show the entries.

It won't be able to support unread messages until the OPDS system supports authentication, since unread messages in ComiXed are on a per-user basis; i.e., a comic might be marked as unread for me but marked as read for you.

Another question for you: what file formats are in the library you're using to test? Right now CX supports CBR and CBZ with some support for CB7.

**Comment by Nosirus** [comment] 2019-04-17 12:36
Only from CBZ I had everything converted with comicrack to be able to write comicvine information directly into it

**Comment by mcpierce** [comment] 2019-04-17 12:49
Okay. I don't have an android device to test with on my end. Can you point me to something I can use on a Linux machine for testing the OPDS system as it's fleshed out?

**Comment by Nosirus** [comment] 2019-04-17 16:08
I do not know linux or windows software for well tested opds an idea?

To be sure to exclude my network or other problems (firewall etc ..) I try Ubooquity with opds, I had no problems to make it work on android and ipad

**Comment by mcpierce** [comment] 2019-04-17 19:39
Okay. We'll keep those things in mind as the OPDS system is further developed so we can make it robust and stable.

**Comment by bareheiny** [comment] 2019-04-25 07:17
Just to add to this, OPDS doesn't seem to work with Windows 10 and Variant as the reader.  

Ubooquity and Variant work fine.

Using the OPDS URL in Edge returns a similar set of text as in Nosirus's image, just not as well formatted.

**Comment by mcpierce** [comment] 2019-04-25 12:00
@bareheiny @Nosirus What JDK are each of you using? If you could, please go to the command line and paste the output from the command in a reply:

    java -version

**Comment by bareheiny** [comment] 2019-04-25 21:00
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

**Comment by mcpierce** [comment] 2019-04-27 11:14
I think the issue here is that, when accessing the root OPDS folder, its return type is "application/json" rather than "application/atom+xml" as it should be.

**Comment by mcpierce** [comment] 2019-04-27 17:56
I also picked up an Android tablet today to start working on this bug. I'm focused now on #445 and the related tickets to that, which will eventually feed into making the OPDS system more user-friendly. So this bug may not get much loving for a few weeks while I'm doing those other tasks. But rest assured this is going to get fixed.

**Comment by mcpierce** [comment] 2019-04-27 18:09
I see the error that was reported initially:

```
2019-04-27 14:02:07.070  WARN 74305 --- [nio-7171-exec-3] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation]
```

This is happening on a Mac, so I don't think the problem is related to either the runtime environment for the JAR file nor the JDK version being used. Look at the headers coming from the client (in this case I'm using Challenger Viewer):

```
2019-04-27 14:02:06.724 DEBUG 74305 --- [nio-7171-exec-1] o.c.web.opds.OPDSRequestInterceptor      : Header[connection]=Keep-Alive
2019-04-27 14:02:06.724 DEBUG 74305 --- [nio-7171-exec-1] o.c.web.opds.OPDSRequestInterceptor      : Header[user-agent]=Apache-HttpClient/UNAVAILABLE (java 1.5)
```

The client isn't telling ComiXed what sort of data it can handle. By comparison, Chunk (on iPad) sends the following headers:

```
2019-04-27 14:07:16.362 DEBUG 74305 --- [nio-7171-exec-5] o.c.web.opds.OPDSRequestInterceptor      : Header[accept]=*/*
2019-04-27 14:07:16.362 DEBUG 74305 --- [nio-7171-exec-5] o.c.web.opds.OPDSRequestInterceptor      : Header[accept-language]=en-us
2019-04-27 14:07:16.362 DEBUG 74305 --- [nio-7171-exec-5] o.c.web.opds.OPDSRequestInterceptor      : Header[connection]=keep-alive
2019-04-27 14:07:16.362 DEBUG 74305 --- [nio-7171-exec-5] o.c.web.opds.OPDSRequestInterceptor      : Header[accept-encoding]=gzip, deflate
2019-04-27 14:07:16.362 DEBUG 74305 --- [nio-7171-exec-5] o.c.web.opds.OPDSRequestInterceptor      : Header[user-agent]=Chunky/2.5.9002 CFNetwork/978.0.7 Darwin/18.5.0
```

You can see where it explicitly says it'll accept **any** content as a reply. So I'll have to look at how to tell the OPDS system to not treat a lack of an accept header as an error condition.

**Closed** 2019-11-12 13:54 UTC
Labels: bug, critical, help wanted, opds
