### ISSUE TITLE
[DISCUSSION] Is ComiXed available as a Container {Docker)?

### ISSUE THREAD

**Issue by comccoy** [mcpierce/comixed#302] opened 2018-11-17 17:22 UTC
With just Java jdk and a .jar file this looks like a perfect candidate for being delivered in a docker container. Is this planned?

**Comment by mcpierce** [comment] 2018-11-17 19:09
It hasn't been discussed as of yet, but I would love to see that. If someone with more Docker-chops than myself can do it that'd be great!

**Comment by comccoy** [comment] 2018-11-17 23:14
I might poke around with it but I feel moderately experienced at running containers but have never built one. Ideal for me would be something hosting at linuxserver.io. I'm really hoping someone who knows docker inside and out would whip something up way faster than I would fumble through.

**Comment by mcpierce** [comment] 2018-11-18 03:16
I'd appreciate if you took an initial stab at it. You probably have more
experience at creating Docker containers than me.

**Comment by FrancisKunz** [comment] 2019-04-05 19:28
Any news on this "Dockerization"

**Comment by mcpierce** [comment] 2019-04-06 13:18
> Any news on this "Dockerization"

Not yet, unfortunately. There's been a lot of feature development, but nothing for Docker packaging. Though I'd be more than happy for someone to contribute this feature to the project.

Otherwise, I can move it to our 0.5 release and take a stab at it then.

**Comment by Jakanapes** [comment] 2019-05-03 14:32
I managed to get the environment mostly set up.

https://github.com/Jakanapes/comixed/blob/develop/Dockerfile

`docker build -t comixed .`

`docker run -it comixed bash`

However, the build command isn't completing yet.  Looks like some deprecation warnings and it needs Chromeheadless.  I'll try to get back to it over the weekend.

The base docker image I used did use OpenJDK, not sure if that's going to cause any issues.

**Comment by mcpierce** [comment] 2019-05-03 19:34
I don't think it should matter if it's OpenJDK vs. an Oracle JDK. Which JDK level is it?

And thank you so much for this! I look forward to using this! 😄

**Comment by Jakanapes** [comment] 2019-05-03 19:51
```bash
root@df0ad112605a:/home/work/~/comixed# java --version
openjdk 10 2018-03-20
OpenJDK Runtime Environment Zulu10.1+11 (build 10+46)
OpenJDK 64-Bit Server VM Zulu10.1+11 (build 10+46, mixed mode)
```

If that's an issue, can always change the base image.

I can add chromium-browser to the apt-get, which let's me define CHROME_BIN, but the problem is getting it to run in Docker

```bash
[INFO] 03 05 2019 23:07:34.863:INFO [karma]: Karma v2.0.5 server started at http://0.0.0.0:9876/
[INFO] 03 05 2019 23:07:34.883:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
[INFO] 03 05 2019 23:07:34.888:INFO [launcher]: Starting browser ChromeHeadless
[INFO] 03 05 2019 23:07:35.305:ERROR [launcher]: Cannot start ChromeHeadless
[INFO] 	[0503/230735.074191:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```

In theory, I should be able to get past this by using the `--privileged` option.  That would just be a work around, but it's not doing the trick.

The other option might be to use the `isDocker` plugin for karma, but I've been hesitant to dip into the actual code just yet.

I'd like to get it running first and then go back and look at trying to slim it up, maybe using an alpine linux base.

I'm a docker dabbler at best, so it's possible that I've done something completely ridiculous as well.

**Comment by mcpierce** [comment] 2019-05-03 21:06
I'm not aware of any problem with using JDK10 to run JDK8 code. We can test and see. I do plan at some point to upgrade the JDK requirement to someone more modern, but want to wait till CX gets more adoption and know better what people are using.

The output I'm seeing above is from the maven build output, specifically the comixed-frontend module when it's attempting to run the Jasmine tests. You can bypass that by passing "-DskipTests" to the build environment within the container. Not the best thing, since we'd ultimate want to run the tests to be sure the environment is sound. But doing that could get you past this hurdle for now.

**Comment by Jakanapes** [comment] 2019-05-03 21:11
I've gotten past that point, finally.  I added the `is-docker` module and updated the karma conf.

So far, I've got it working to the point where I can build the image, then run it with 

`docker run -it -p 7171:7171/tcp comixed bash`

Looks OK, I can log in and click around.  Still to do:

Figure out a mount for the directory on host that contains the comics and mount the database on host so it will persist between runs.

**Comment by Jakanapes** [comment] 2019-05-03 21:20
hmm, actually, it's not running the `CMD` for some reason, I'll have to look at the options again.

However, if you run `java -jar comixed-app/target/comixed-app-*.jar` from the container once it's running, you should be able to access the site

**Comment by Jakanapes** [comment] 2019-05-04 15:41
OK, latest version of my repo is running automatically when started with `docker run -it -p 7171:7171/tcp comixed`.

Now I think I just need a bind mount for the comic directory and a named volume for the database

**Comment by Jakanapes** [comment] 2019-05-04 19:49
getting closer

`docker run -it -p 7171:7171/tcp -v "/Volumes/Hyperborea/Comics Temp/Holding Zone":/comic_dir comixed`


![Screen Shot 2019-05-04 at 2 47 38 PM](https://user-images.githubusercontent.com/239207/57184078-a6347800-6e7b-11e9-8944-dc89a584ccdf.jpg)


That's all it does, though, when you select a comic it just sits there.  I"m sure I'm missing something about permissions or opening the container to the internet or something.

**Comment by mcpierce** [comment] 2019-05-05 16:47
Looking really good!

Mentioning the location for the comic directory, I think a recent request (#451) will work together with this nice. Would it make the docker image easier to run if we require the comic files be relative to the the mount point?

**Comment by mcpierce** [comment] 2019-05-05 16:49
Looking really good!

Mentioning the location for the comic directory, I think a recent request (#452) will work together with this nice. Would it make the docker image easier to run if we require the comic files be relative to the the mount point?

**Comment by Jakanapes** [comment] 2019-05-06 17:38
I kept wondering why I wasn't able to complete the import process, either in the docker container or on the host and I noticed a bunch of these warnings in the output

`WARN 81716 --- [io-7171-exec-10] o.c.w.a.ComiXedAuthenticationFilter      : couldn't find bearer string, will ignore the header`

**Comment by mcpierce** [comment] 2019-05-06 18:53
You can safely ignore them, they're unrelated to the importing process. That's the auth filter saying it couldn't find the JWT token on a request is received from your browser.

**Comment by Jakanapes** [comment] 2019-05-06 19:02
OK, but I click import, I get the list of comics it has found and that's it.  According to the quickstart, it seems like there should be more buttons to finish the import?

I even tried downloading the jar from the latest release and it's not functioning on my mac.

**Comment by mcpierce** [comment] 2019-05-06 19:31
Sorry, that's a little out of date. I need to fix that.

The newer way to interact is to just click on a comic cover on the page. It will get greyed out, showing it's been selected. (this works across any view list this). Then click on Library -> Selected Comics and it will show you a sidebar of all the comics you've selected. There's a dropdown button that you can click on the start the import process.

**Comment by Jakanapes** [comment] 2019-05-06 19:42
aha, thanks, that works like a charm

**Comment by Jakanapes** [comment] 2019-05-07 13:20
OK, so I built the initial image and uploaded it to docker hub

https://cloud.docker.com/repository/docker/jakanapes/comixed/general

It can be run with

`docker run -it -p 7171:7171/tcp -v /PATH/TO/COMICS:/comic_dir -v comixed_db:/home/root/.comixed/comixed jakanapes/comixed`

I've also added a docker-compose.yml.EXAMPLE to my fork.  Just copy and rename it to docker-compose.yml and replace the `{/PATH/TO/COMICS}` with the real absolute path, then do `docker-compose up`


This initial image is overly large, so it needs to be tweaked to lower the size, but this is a good start.

**Comment by mcpierce** [comment] 2019-05-08 16:20
Can you submit a PR for the docker files and I'll merge them into the project?

**Comment by comccoy** [comment] 2019-05-23 19:00
Glad to see some movement on this. I had it on my list for several months and have just not had the cycles to dedicate. Thanks for all the hard work!

**Comment by Shadowghost** [comment] 2019-08-03 14:05
Since this request was remove from the milestone, do we have a working official docker-image or dockerfile? I couldn't find anything related to this in the repo or the docs. I'd be really interested in it and you could automate builds on dockerhub when new releases/commits are being pushed.

**Comment by mcpierce** [comment] 2019-08-03 17:31
@Shadowghost I believe that's what @Jakanapes has done for us. See his response above.

**Comment by Shadowghost** [comment] 2019-08-03 20:09
Yeah, seems like everything works but the dockerfile just wasn't PRed so I was courious why that is the case. Seems like @Jakanapes just didn't follow the request to PR it :) - would be nice if he PRs it now, so everything is available here.

**Comment by PiDockMedia** [comment] 2019-11-06 02:02
Is this enhancement dead? @Jakanapes seems to have disappeared sadly.

**Comment by mcpierce** [comment] 2019-11-08 14:30
@PiDockMedia I'm not sure what @Jakanapes 's status is, but please feel free to take the PR an extend it if you'd like.

**Comment by PiDockMedia** [comment] 2019-11-10 16:14
I've been poking at this a bit and have not had much success. I think I have hit the same wall @Jakanapes did with a chromium issue. It freezes for a very long time (minutes) at:

`
2019-11-10 15:51:08.680  INFO 192 --- [           main] org.comixed.service.file.FileService     : Preparing to import 4 comic files: delete blocked pages=No ignore metadata=Yes`

Eventually it continues and I get 

`[INFO] --- frontend-maven-plugin:1.7.5:yarn (Angular tests) @ comixed-frontend ---
[INFO] Running 'yarn run test' in /comixed/comixed-frontend
[INFO] yarn run v1.13.0
[INFO] $ ng test
[INFO] 10 11 2019 16:08:37.602:INFO [karma-server]: Karma v3.1.4 server started at http://0.0.0.0:9876/
[INFO] 10 11 2019 16:08:37.605:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
[INFO] 10 11 2019 16:08:37.612:INFO [launcher]: Starting browser ChromeHeadless
[INFO] 10 11 2019 16:08:38.297:ERROR [launcher]: Cannot start ChromeHeadless
[INFO] 	[1110/160837.658766:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
[INFO] 
[INFO] 10 11 2019 16:08:38.298:ERROR [launcher]: ChromeHeadless stdout: 
[INFO] 10 11 2019 16:08:38.298:ERROR [launcher]: ChromeHeadless stderr: [1110/160837.658766:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
[INFO] 
[INFO] 10 11 2019 16:08:38.405:INFO [launcher]: Trying to start ChromeHeadless again (1/2).
[INFO] 10 11 2019 16:08:38.656:ERROR [launcher]: Cannot start ChromeHeadless
[INFO] 	[1110/160838.496727:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
[INFO] 
[INFO] 10 11 2019 16:08:38.656:ERROR [launcher]: ChromeHeadless stdout: 
[INFO] 10 11 2019 16:08:38.656:ERROR [launcher]: ChromeHeadless stderr: [1110/160838.496727:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
[INFO] 
[INFO] 10 11 2019 16:08:38.689:INFO [launcher]: Trying to start ChromeHeadless again (2/2).
[INFO] 10 11 2019 16:08:38.843:ERROR [launcher]: Cannot start ChromeHeadless
[INFO] 	[1110/160838.770617:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
[INFO] 
[INFO] 10 11 2019 16:08:38.843:ERROR [launcher]: ChromeHeadless stdout: 
[INFO] 10 11 2019 16:08:38.843:ERROR [launcher]: ChromeHeadless stderr: [1110/160838.770617:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
[INFO] 
[INFO] 10 11 2019 16:08:39.152:ERROR [launcher]: ChromeHeadless failed 2 times (cannot start). Giving up.
[INFO] 
[INFO] 
[INFO] Suites and tests results:
[INFO] 
[INFO] 
[INFO] Browser results:
[INFO] 
[INFO] 
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for comixed-parent 0.4.9-SNAPSHOT:
[INFO] 
[INFO] comixed-parent ..................................... SUCCESS [  0.856 s]
[INFO] comixed-library .................................... SUCCESS [01:56 min]
[INFO] comixed-tasks ...................................... SUCCESS [  5.708 s]
[INFO] comixed-services ................................... SUCCESS [16:37 min]
[INFO] comixed-rest-api ................................... SUCCESS [  8.883 s]
[INFO] comixed-frontend ................................... FAILURE [ 45.997 s]
[INFO] comixed-app ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19:36 min
[INFO] Finished at: 2019-11-10T16:08:39Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.5:yarn (Angular tests) on project comixed-frontend: Failed to run task: 'yarn run test' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :comixed-frontend
The command '/bin/sh -c mvn clean package' returned a non-zero code: 1
`

**Comment by PiDockMedia** [comment] 2019-11-10 16:51
Okay, just posted and removed a lengthy error/question. It looks like running this in docker required some extra changes. Keep heart I am working on this. I'm a sdcripter/engineer and not a developer so it is a slower process for me.

**Comment by PiDockMedia** [comment] 2019-11-12 03:05
I made a lot of progress this long weekend. I worked a lot on @Jakanapes process that was to build the latest snapshot on the fly. After a lot of build issues I decided to switch grabbing the .jar file which drastically simplifies the process. I have a bit of cleanup to do but then I'll submit my changes.

**Comment by PiDockMedia** [comment] 2019-11-14 01:03
Alright friends, you should be able to run this. NOTE: I have only done a container with the 3.3.0 version as it was the latest actual release I saw. If I can get a verification or two I will move on to the latest snapshot of 4.9.  Make sure you set a local path to where you want your comics to be stored and the local path to where the comixed db should live.

`docker run -it -p 7171:7171/tcp -v /PATH/TO/COMICS:/comic_dir -v /PATH/TO/COMIXEDDB:/root/.comixed pidockmedia:comixed:latest`

**Comment by PiDockMedia** [comment] 2019-11-15 00:18
The latest and release docker images are both 0.4.0 now.

**Comment by mcpierce** [comment] 2019-11-15 02:35
@PiDockMedia I've created a docker repository for the project. Can I add you there as a collaborator to help me with maintaining it?

**Comment by comccoy** [comment] 2019-11-15 03:18
That sounds like a great idea.

**Comment by mcpierce** [comment] 2019-11-15 16:09
@comccoy Are you @PiDockMedia ? I tried inviting PiDockMedia on the Docker hub site and it didn't show up.

**Comment by PiDockMedia** [comment] 2019-11-15 19:31
Sorry, yes I should be there as pidockmedia. 

https://hub.docker.com/r/pidockmedia

**Comment by PiDockMedia** [comment] 2019-11-16 13:14
It looks like the push was successful.

docker run -it -p 7171:7171/tcp -v /PATH/TO/COMICS:/comic_dir -v /PATH/TO/COMIXEDDB:/root/.comixed mcpierce/comixed:release

**Comment by mcpierce** [comment] 2019-11-17 14:16
Outstanding! And that you for that work! I'm going to close this ticket since the goal was completed.

**Closed by mcpierce** 2019-11-17 14:16 UTC
Labels: discussion, help wanted
