### ISSUE TITLE
Functionality to rename / move issues (individuallyand in bulk).

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#448] opened 2019-04-28 22:15 UTC
On import, comic files may not be named to a users liking.

I would like the functionality to re-name files using a user-defined format using a mix of metadata and free-text (as required).

For example, I may choose to store my comics in publisher folders in a directory called "Comics", naming the files using series, volume, number and publication date.

The file path would then be (once the files were processed):

\Comics\Image\Spawn Vol.1992 #400 (2030/12/31).cbz
\Comics I don't really like\Archie Adventures Series\Adventures of the Fly Vol.1959 #1 (1959/8/1).cbz

The user would need to be given options when a target file name is already in use (the standard replace, ignore, re-name with numeric suffix).

**Comment by mcpierce** [comment] 2019-04-30 00:17
This is the intention of #79. I'm going to mark this ticket as relating back to that, as it adds to the consolidation ticket the file renaming aspect.

**Comment by mcpierce** [comment] 2019-10-28 12:02
Closing this story as a duplicate of #79 to narrow down the focus of this release. The functionality is going to be added, so please follow the other ticket for when it lands.

**Closed by mcpierce** 2019-10-28 12:02 UTC
Labels: backend, enhancement, frontend
